name: chatroom
description: "A new Flutter project."
repository: "https://github.com/davidnwaneri/chatroom"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  meta: ^1.11.0
  talker_dio_logger: ^2.4.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/google_fonts/inconsolata/
